INSERT INTO `artists`(`name`, `is_group`)
VALUES ('Eminem', '0'),
('Dr. Dre', '0'),
('2Pac', '0'),
('Wu-Tang Clan', '1'),
('Outkast', '1'),  
('Denzel Curry', '0'),  
('JID', '0'),
('Kendrick Lamar', '0'),  
('J. Cole', '0'),  
('Lil Wayne', '0'),  
('Joey Bada$$', '0'),  
('The Game', '0'),  
('Ice Cube', '0'), 
('DMX', '0'),  
('Lauryn Hill', '0'),  
('Makaveli', '0'), 
('Nas', '0'),
('Big L', '0'),  
('Kids See Ghosts', '1'),  
('Kanye West', '0'),  
('The Notorious B.I.G', '0'),  
('50 Cent', '0'),  
('Fugees', '1'),  
('Ghostface Killah', '0'),  
('GZA', '0'),  
('Mos Def', '0'),  
('Black Star', '1'),  
('Big Pun', '0'),
('Snoop Dogg', '0'),  
('Gang Starr', '1'),  
('IDK', '0'),  
('Ol\' Dirty Bastard', '0'),
('Souls Of Mischief', '1'), 
('The Pharcyde', '1'),  
('Warren G', '0'),  
('Isaiah Rashad', '0'),  
('Westside Gunn', '0'),  
('Tyler, The Creator', '0'),  
('Benny The Butcher', '0'),  
('Racionais MC’s', '1'),  
('BK', '0'),  
('O Rappa', '1'),  
('Charlie Brown Jr.', '1'),  
('Febem & Fleezus', '1'), 
('Sant', '0'),
('Jay-Z', '0'),
('N.W.A.', '1'),
('Mobb Deep', '1'), 
('Febem', '0'),
('Raekwon', '0'),
('MF DOOM', '0'),
('Clipse', '1'),
('A Tribe Called Quest', '1'),
('Djonga', '0'),
('Emicida', '0');

INSERT INTO `albums`(`name`, `release_year`, `duration`, `no_tracks`)
VALUES ('8 Mile (Music From and Inspired By The Motion Picture)', 2002, '01:08:00', 16),
('2001', 1999, '01:08:00', 23),
('All Eyez On Me', 1996, '02:12:00', 27),
('Enter the Wu-Tang (36 Chambers)', 1993, '01:10:00', 15),
('Aquemini', 1998, '01:14:00', 16),
('ATLiens', 1996, '00:57:00', 15),
('Illmatic', 1994, '00:39:00', 10),
('The Big Picture', 2000, '00:55:00', 16),
('Good Kid, M.A.A.D City', 2001, '01:17:00', 14),
('2014 Forest Hills Drive', 2014, '01:04:00', 13),
('Tha Carter V', 2018, '01:27:00', 23),
('1999', 2012, '01:01:00', 15),
('To Pimp a Butterfly', 2015, '01:18:00', 16),
('UNLOCKED', 2020, '00:17:00', 8),
('The Forever Story', 2022, '01:06:00', 16),
('Stankonia', 2000, '01:13:00', 24),
('Only Built 4 Cuban Linx…', 1994, '01:13:00', 18),
('The Score', 1996, '01:09:00', 15),
('Supreme Clientele', 2000, '01:04:00', 21),
('Black On Both Sides', 1999, '01:11:00', 17),
('Stillmatic', 2001, '00:56:00', 14),
('Magic', 2021, '00:29:00', 9),
('The Don Killuminati: The 7 Day Theory', 1996, '00:59:00', 12),
('Life After Death', 1997, '01:49:00', 24),
('Straight Outta Compton', 1988, '01:00:00', 13),
('The Infamous', 1995, '01:06:00', 16),
('The Sun\'s Tirade', 2016, '01:03:00', 17),
('93 \'til Infinity', 1993, '00:53:00', 14),
('Bizarre Ride II The Pharcyde', 1992, '00:56:00', 16),
('Regulate... G Funk Era', 1994, '01:02:00', 18),  
('Mos Def & Talib Kweli Are Black Star', 1998, '00:49:00', 13),
('Capital Punishment', 1998, '01:11:00', 24),
('Doggystyle', 1993, '00:52:00', 13),
('Moment Of Truth', 1998, '01:18:00', 20),
('IDK & FRIENDS :)', 2018, '00:00:16', 7),
('Return to the 36 Chambers: The Dirty Version', 1994, '01:07:00', 17),
('Lifestylez Ov Da Poor & Dangerous', 1995, '00:48:00', 12),
('MM..FOOD', 2004, '00:48:00', 15),
('My Beautiful Dark Twisted Fantasy', 2010, '01:05:00', 13),
('Damn', 2017, '00:54:00', 14),
('Ye', 2018, '00:23:00', 7),
('Kids See Ghosts', 2018, '00:23:00', 7),
('4:44', 2017, '00:36:00', 10),
('The Eminem Show', 2002, '01:12:00', 19),
('The Marshall Mathers LP', 2000, '01:12:00', 18),
('Get Rich Or Die Tryin\'', 2003, '01:14:00', 20),
('The Blueprint', 2001, '01:03:00', 15),
('The Documentary', 2004, '01:09:00', 18),
('The Predator', 1992, '00:56:00', 16),
('Sobrevivendo no Inferno', 1997, '01:13:00', 12),
('Nada Como um Dia Após o Outro Dia, Vol. 1 & 2', 2002, '01:50:00', 21),
('Castelos & Ruínas', 2016, '00:42:00', 13),
('Gigantes', 2018, '00:49:00', 13),
('7 Vezes', 2008, '01:04:00', 14),
('Lado B Lado A', 1999, '00:56:00', 12),
('Preço Curto, Prazo Longo', 1999, '01:08:00', 25),
('100% Charlie Brown Jr – Abalando A Sua Fábrica', 2001, '00:36:00', 12),
('Camisa 10 joga bola até na chuva', 2009, '00:51:00', 13),
('BRIME!', 2020, '00:20:00', 6),
('BRIME! (Deluxe)', 2023, '00:39:00', 11),
('O Que Separa os Homens dos Meninos, Vol. 1', 2015, '00:18:00', 5),
('Rap dos Novos Bandidos', 2021, '00:33:00', 15),
('Ainda É o Rap dos Novos Bandidos', 2022, '00:18:00', 9),
('CONVICTO', 2024, '00:29:00', 10),
('Melt My Eyez See Your Future', 2022, '00:45:00', 14),
('I Am...', 1999, '01:04:00', 16),
('It''s Dark And Hell Is Hot', 1998, '01:05:00', 19),
('The Miseducation of Lauryn Hill', 1998, '01:17:00', 16),
('2000', 2022, '00:56:00', 15),
('IGOR', 2019, '00:39:00', 12),
('Call Me If You Get Lost', 2021, '00:52:00', 16),
('Pray for Paris', 2020, '00:36:00', 12),
('Tana Talk 4', 2022, '00:40:00', 12),
('Reasonable Doubt', 1996, '00:59:00', 15),
('Ready to Die', 1994, '01:16:00', 19),
('Get Rich Or Die Tryin'' - The Original Motion Picutre Soundtrack', 2005, '01:05:00', 18),
('Me Against The World', 1995, '01:05:00', 15),
('The Massacre', 2005, '01:17:00', 22),
('ABAIXO DO RADAR', 2024, '00:25:00', 10),
('Mr. Morale & The Big Steppers', 2022, '01:18:00', 19),
('Let God Sort Em Out', 2025, '00:40:00', 13),
('The Low End Theory', 1991, '00:47:00', 14),
('O MENINO QUE QUERIA SER DEUS', 2018, '00:39:00', 10),
('Heresia', 2017, '00:33:00', 10),
('Pra Quem Já Mordeu Um Cachorro por Comida Até Que Eu Cheguei Longe', 2009, '01:18:00', 25);

INSERT INTO `songs`(`name`, `artist_id`, `album_id`, `feat_name`, `from_country`) 
VALUES ('Rabbit Run', 1, 1, '', 'Estados Unidos'),
('Lose Yourself', 1, 1, '', 'Estados Unidos'),
('Forgot About Dre', 2, 2, 'Eminem', 'Estados Unidos'),
('The Watcher', 2, 2, 'Eminem & Knoc-Turn''al', 'Estados Unidos'),
('What''s The Difference', 2, 2, 'Eminem & Xzibit', 'Estados Unidos'),
('Still D.R.E.', 2, 2, 'Snoop Dogg', 'Estados Unidos'),
('The Next Episode', 2, 2, 'Snoop Dogg', 'Estados Unidos'),
('Ambitionz Az A Ridah', 3, 3, '', 'Estados Unidos'),
('Can''t C Me', 3, 3, '', 'Estados Unidos'),
('Picture Me Rollin''', 3, 3, 'Big Syke & C-PO & Danny Boy', 'Estados Unidos'),
('All Eyez On Me', 3, 3, 'Big Syke', 'Estados Unidos'),
('Skandalouz', 3, 3, 'Nate Dogg', 'Estados Unidos'),
('2 Of Amerikaz Most Wanted', 3, 3, 'Snoop Dogg', 'Estados Unidos'),
('Only God Can Judge Me', 3, 3, 'Rappin'' 4-Tay', 'Estados Unidos'),
('Tradin War Stories', 3, 3, 'Storm & C-Bo & Outlawz & C-PO', 'Estados Unidos'),
('I Ain''t Mad At Cha', 3, 3, 'Danny Boy', 'Estados Unidos'),
('Check Out Time', 3, 3, '', 'Estados Unidos'),
('Bring Da Ruckus', 4, 4, '', 'Estados Unidos'),
('Shame On a Nigga', 4, 4, '', 'Estados Unidos'),
('Da Mystery of Chessboxin''', 4, 4, '', 'Estados Unidos'),
('Wu-Tang Clan Ain''t Nuthing ta F'' Wit', 4, 4, '', 'Estados Unidos'),
('C.R.E.A.M (Cash Rules Everything Around Me)', 4, 4, '', 'Estados Unidos'),
('Tearz', 4, 4, '', 'Estados Unidos'),
('Method Man', 4, 4, '', 'Estados Unidos'),
('Aquemini', 5, 6, '', 'Estados Unidos'),
('Rosa Parks', 5, 5, '', 'Estados Unidos'),
('Skew It on the Bar-B', 5, 5, 'Raekwon', 'Estados Unidos'),
('Da Art of Storrytellin'' (Pt.1)', 5, 5, '', 'Estados Unidos'),
('SpottieOttieDopaliscious', 5, 5, '', 'Estados Unidos'),
('Walkin', 6, 65, '', 'Estados Unidos'),
('Melt Session #1', 6, 65, 'Robert Glasper', 'Estados Unidos'),
('The Last', 6, 65, '', 'Estados Unidos'),
('Mental', 6, 65, 'Saul Williams & Bridget Perez', 'Estados Unidos'),
('Angelz', 6, 65, 'Karriem Riggins', 'Estados Unidos'),
('X-Wing', 6, 65, '', 'Estados Unidos'),
('The Smell Of Death', 6, 65, '', 'Estados Unidos'),
('The Ills', 6, 65, '', 'Estados Unidos'),
('Ain''t No Way', 6, 65, '6LACK & Rico Nasty & JID & Jasiah & Kitty Ca$h', 'Estados Unidos'),
('Sanjuro', 6, 65, '454', 'Estados Unidos'),
('Surround Sound', 7, 15, '21 Savage & Baby Tate', 'Estados Unidos'),
('Raydar', 7, 15, '', 'Estados Unidos'),
('Dance Now', 7, 15, 'Kenny Mason', 'Estados Unidos'),
('Crack Sandwich', 7, 15, '', 'Estados Unidos'),
('Kody Blue 31', 7, 15, '', 'Estados Unidos'),
('Sistanem', 7, 15, '', 'Estados Unidos'),
('Stars', 7, 15, 'Yasiin Bey', 'Estados Unidos'),
('Lauder Too', 7, 15, 'Ravyn Lenae & Eryn Allen Kane', 'Estados Unidos'),
('Can''t Make U Change', 7, 15, 'Ari Lennox', 'Estados Unidos'),
('2007', 7, 15, '', 'Estados Unidos'),
('ATLiens', 5, 6, '', 'Estados Unidos'),
('Two Dope Boyz (In a Cadillac)', 5, 6, '', 'Estados Unidos'),
('Jazzy Belle', 5, 6, '', 'Estados Unidos'),
('Elevators (Me & You)', 5, 6, '', 'Estados Unidos'),
('Ova Da Wudz', 5, 6, '', 'Estados Unidos'),
('Decatur Psalm', 5, 6, '', 'Estados Unidos'),
('N.Y. State of Mind', 17, 7, '', 'Estados Unidos'),
('The World Is Yours', 17, 7, '', 'Estados Unidos'),
('Halftime', 17, 7, '', 'Estados Unidos'),
('Life''s a Bitch', 17, 7, 'AZ & Olu Dara', 'Estados Unidos'),
('One Love', 17, 7, 'Q-Tip', 'Estados Unidos'),
('Represent', 17, 7, '', 'Estados Unidos'),
('It Ain''t Hard to Tell', 17, 7, '', 'Estados Unidos'),
('Memory Lane (Sittin'' in da Park)', 17, 7, '', 'Estados Unidos'),
('The Heist Revisited', 18, 8, '', 'Estados Unidos'),
('Ebonics (Criminal Slang)', 18, 8, '', 'Estados Unidos'),
('Size ''Em Up', 18, 8, '', 'Estados Unidos'),
('98 Freestyle', 18, 8, '', 'Estados Unidos'),
('Deadly Combination', 18, 8, '2Pac', 'Estados Unidos'),
('Flamboyant', 18, 8, '', 'Estados Unidos'),
('Platinum Plus', 18, 8, 'Big Daddy Kane', 'Estados Unidos'),
('Sing About Me, I''m Dying Of Thirst', 8, 9, '', 'Estados Unidos'),
('Bitch, Don''t Kill My Vibe', 8, 9, '', 'Estados Unidos'),
('Backseat Freestyle', 8, 9, '', 'Estados Unidos'),
('Money Trees', 8, 9, 'Jay Rock', 'Estados Unidos'),
('m.A.A.d city', 8, 9, 'MC Eiht', 'Estados Unidos'),
('Real', 8, 9, 'Anna Wise', 'Estados Unidos'),
('Swimming Pools (Drank)', 8, 9, '', 'Estados Unidos'),
('No Role Modelz', 9, 10, '', 'Estados Unidos'),
('Wet Dreamz', 9, 10, '', 'Estados Unidos'),
('03'' Adolescence', 9, 10, '', 'Estados Unidos'),
('Love Yourz', 9, 10, '', 'Estados Unidos'),
('Mona Lisa', 10, 11, 'Kendrick Lamar', 'Estados Unidos'),
('Survival Tactits', 11, 12, 'Capital Steez', 'Estados Unidos'),
('Righteous Minds', 11, 12, '', 'Estados Unidos'),
('Where It''$ At?', 11, 12, 'Kirk Knight', 'Estados Unidos'),
('Summer Knights', 11, 12, '', 'Estados Unidos'),
('Alright', 8, 13, '', 'Estados Unidos'),
('Wesley''s Theory', 8, 13, 'George Clinton & Thundercat', 'Estados Unidos'),
('King Kunta', 8, 13, '', 'Estados Unidos'),
('These Walls', 8, 13, 'Bilal & Anna Wise & Thundercat', 'Estados Unidos'),
('U', 8, 13, '', 'Estados Unidos'),
('I', 8, 13, '', 'Estados Unidos'),
('Complexion (A Zulu Love)', 8, 13, 'Rapsody', 'Estados Unidos'),
('Mortal Man', 8, 13, '', 'Estados Unidos'),
('Hood Politics', 8, 13, '', 'Estados Unidos'),
('The Blacker The Berry', 8, 13, '', 'Estados Unidos'),
('DIET_', 6, 14, '', 'Estados Unidos'),
('Take_it_Back_v2', 6, 14, '', 'Estados Unidos'),
('Lay_Up.m4a', 6, 14, '', 'Estados Unidos'),
('So.Incredible.pkg', 6, 14, '', 'Estados Unidos'),
('Pyro (leak 2019)', 6, 14, '', 'Estados Unidos'),
('Small World', 17, 66, '', 'Estados Unidos'),
('Hate Me Now', 17, 66, 'Diddy', 'Estados Unidos'),
('Undying Love', 17, 66, '', 'Estados Unidos'),
('Red Velvet', 5, 16, '', 'Estados Unidos'),
('So Fresh, So Clean', 5, 16, '', 'Estados Unidos'),
('Ms. Jackson', 5, 16, '', 'Estados Unidos'),
('Snappin'' & Trappin''', 5, 16, 'Killer Mike & J-Sweet', 'Estados Unidos'),
('Humble Mumble', 5, 16, 'Erykah Badu', 'Estados Unidos'),
('?', 5, 16, '', 'Estados Unidos'),
('Toilet Tisha', 5, 16, '', 'Estados Unidos'),
('B.O.B - Bombs Over Baghdad', 5, 16, '', 'Estados Unidos'),
('Ice Cream', 50, 17, 'Ghostface Killah & Method Man & Cappadonna', 'Estados Unidos'),
('Criminology', 50, 17, 'Ghostface Killah', 'Estados Unidos'),
('Incarcerated Scarfaces', 50, 17, '', 'Estados Unidos'),
('Guillotine (Swordz)', 50, 17, 'Ghostface Killah & Inspectah Deck & GZA', 'Estados Unidos'),
('Glaciers of Ice', 50, 17, 'Ghostface Killah & Masta Killa', 'Estados Unidos'),
('Verbal Intercourse', 50, 17, 'Ghostface Killah & Nas', 'Estados Unidos'),
('Heaven & Hell', 50, 17, 'Ghostface Killah', 'Estados Unidos'),
('Workin'' Out', 7, NULL, '', 'Estados Unidos'),
('Renegade', 46, 47, 'Eminem', 'Estados Unidos'),
('The Ruler''s Back', 46, 47, '', 'Estados Unidos'),
('Takeover', 46, 47, '', 'Estados Unidos'),
('Izzo (H.O.V.A)', 46, 47, '', 'Estados Unidos'),
('Heart Of The City (Ain''t No Love)', 46, 47, '', 'Estados Unidos'),
('Song Cry', 46, 47, '', 'Estados Unidos'),
('Never Change', 46, 47, '', 'Estados Unidos'),
('Lyrical Exercise', 46, 47, '', 'Estados Unidos'),
('Blueprint (Momma Loves Me)', 46, 47, '', 'Estados Unidos'),
('Hate It Or Love It', 12, 48, '50 Cent', 'Estados Unidos'),
('How We Do', 12, 48, '50 Cent', 'Estados Unidos'),
('It Was A Good Day', 13, 49, '', 'Estados Unidos'),
('I Can Feel It', 14, 67, '', 'Estados Unidos'),
('Ruff Ryder''s Anthem', 14, 67, '', 'Estados Unidos'),
('Look Thru My Eyes', 14, 67, '', 'Estados Unidos'),
('Get At Me Dog', 14, 67, 'Sheek', 'Estados Unidos'),
('Let Me Fly', 14, 67, '', 'Estados Unidos'),
('How''s It Goin'' Down', 14, 67, '', 'Estados Unidos'),
('For My Dogs', 14, 67, 'Drag-On & Loose & Big Stan & Kasino', 'Estados Unidos'),
('Ex-Factor', 15, 68, '', 'Estados Unidos'),
('Lost Ones', 15, 68, '', 'Estados Unidos'),
('Doo Wop (That Thing)', 15, 68, '', 'Estados Unidos'),
('Final Hour', 15, 68, '', 'Estados Unidos'),
('When It Hurts so Bad', 15, 68, '', 'Estados Unidos'),
('Forgive Them Father', 15, 68, '', 'Estados Unidos'),
('Every Ghetto, Every City', 15, 68, '', 'Estados Unidos'),
('Can''t Take My Eyes Off of You - (I Love You Baby)', 15, 68, '', 'Estados Unidos'),
('I Used to Love Him', 15, 68, 'Mary J. Blige', 'Estados Unidos'),
('Show Me', 11, 69, '', 'Estados Unidos'),         
('Head High', 11, 69, '', 'Estados Unidos'),
('Brand New 911', 11, 69, 'Westside Gunn', 'Estados Unidos'),
('Wanna Be Loved', 11, 69, 'JID', 'Estados Unidos'),
('PRIDE.', 8, 40, '', 'Estados Unidos'),
('DNA.', 8, 40, '', 'Estados Unidos'),
('ELEMENT.', 8, 40, '', 'Estados Unidos'),
('FEEL.', 8, 40, '', 'Estados Unidos'),
('LOYALTY.', 8, 40, 'Rihanna', 'Estados Unidos'),
('HUMBLE.', 8, 40, '', 'Estados Unidos'),
('FEAR.', 8, 40, '', 'Estados Unidos'),
('LOVE.', 8, 40, 'Zacari', 'Estados Unidos'),
('XXX.', 8, 40, 'U2', 'Estados Unidos'),
('EARFQUAKE', 38, 70, '', 'Estados Unidos'),
('IGOR''S THEME', 38, 70, '', 'Estados Unidos'),
('I THINK', 38, 70, '', 'Estados Unidos'),
('NEW MAGIC WAND', 38, 70, '', 'Estados Unidos'),
('GONE, GONE / THANK YOU', 38, 70, '', 'Estados Unidos'),
('ARE WE STILL FRIENDS?', 38, 70, '', 'Estados Unidos'),
('327', 37, 72, 'Joey Bada$$ & Tyler, The Creator & Billie Essco', 'Estados Unidos'),
('Johnny P''s Caddy', 39, 73, 'J. Cole', 'Estados Unidos'),
('SWEET / I THOUGHT YOU WANTED TO DANCE', 38, 71, 'Brent Faiyaz & Fana Hues', 'Estados Unidos'),
('SIR BAUDELAIRE', 38, 71, 'DJ Drama', 'Estados Unidos'),
('CORSO', 38, 71, '', 'Estados Unidos'),
('WUSYANAME', 38, 71, 'Youngboy Never Broke Again & Ty Dolla $ign', 'Estados Unidos'),
('HOT WIND BLOWS', 38, 71, 'Lil Wayne', 'Estados Unidos'),
('4:44', 46, 43, '', 'Estados Unidos'),
('The Story of O.J.', 46, 43, '', 'Estados Unidos'),
('Family Feud', 46, 43, 'Beyoncé', 'Estados Unidos'),
('Marcy Me', 46, 43, '', 'Estados Unidos'),
('Smile', 46, 43, 'Gloria Carter', 'Estados Unidos'),
('Legacy', 46, 43, '', 'Estados Unidos'),
('Ghost Town', 20, 41, 'PARTYNEXTDOOR', 'Estados Unidos'),
('Feelin'' It', 46, 74, 'Mecca', 'Estados Unidos'),
('Can''t Knock The Hustle', 46, 74, 'Mary J. Blige', 'Estados Unidos'),
('Politics As Usual', 46, 74, '', 'Estados Unidos'),
('Dead Presidents II', 46, 74, '', 'Estados Unidos'),
('Brooklyn''s Finest', 46, 74, 'The Notorius B.I.G', 'Estados Unidos'),
('D''evils', 46, 74, '', 'Estados Unidos'),
('Friend or Foe', 46, 74, '', 'Estados Unidos'),
('Father Time', 8, 80, 'Sampha', 'Estados Unidos'),
('United In Grief', 8, 80, '', 'Estados Unidos'),
('N95', 8, 80, '', 'Estados Unidos'),
('Rich Spirit', 8, 80, '', 'Estados Unidos'),
('Die Hard', 8, 80, 'Blxst & Amanda Reifer', 'Estados Unidos'),
('Count Me Out', 8, 80, '', 'Estados Unidos'),
('Savior', 8, 80, 'Baby Keem & Sam Dew', 'Estados Unidos'),
('Mother I Sober', 8, 80, 'Beth Gibbons', 'Estados Unidos'),
('4th Dimension', 19, 42, 'Louis Prima', 'Estados Unidos'),
('Reborn', 19, 42, '', 'Estados Unidos'),
('Cudi Montage', 19, 42, '', 'Estados Unidos'),
('Kids See Ghosts', 19, 42, 'Yasiin Bey', 'Estados Unidos'),
('Feel The Love', 19, 42, 'Pusha T', 'Estados Unidos'),
('Runaway', 20, 39, 'Pusha T', 'Estados Unidos'),
('Gorgeous', 20, 39, 'Kid Cudi & Raekwon', 'Estados Unidos'),
('POWER', 20, 39, '', 'Estados Unidos'),
('All Of The Lights', 20, 39, '', 'Estados Unidos'),
('Devil In A New Dress', 20, 39, 'Rick Ross', 'Estados Unidos'),
('Things Done Changed', 21, 75, '', 'Estados Unidos'),
('Gimme the Loot', 21, 75, '', 'Estados Unidos'),
('Machine Gun Funk', 21, 75, '', 'Estados Unidos'),
('Warning', 21, 75, '', 'Estados Unidos'),
('Juicy', 21, 75, '', 'Estados Unidos'),
('Everyday Struggle', 21, 75, '', 'Estados Unidos'),
('Big Poppa', 21, 75, '', 'Estados Unidos'),
('Suicidal Thoughts', 21, 75, '', 'Estados Unidos'),
('Who Shot Ya?', 21, 75, '', 'Estados Unidos'),
('Just Playing (Dreams)', 21, 75, '', 'Estados Unidos'),
('What Up Gangsta', 22, 46, '', 'Estados Unidos'),
('Patiently Waiting', 22, 46, 'Eminem', 'Estados Unidos'),
('Many Men (Wish Death)', 22, 46, '', 'Estados Unidos'),
('In Da Club', 22, 46, '', 'Estados Unidos'),
('High All The Time', 22, 46, '', 'Estados Unidos'),
('P.I.M.P', 22, 46, '', 'Estados Unidos'),
('21 Questions', 22, 46, 'Nate Dogg', 'Estados Unidos'),
('Wanksta', 22, 46, '', 'Estados Unidos'),
('White America', 1, 44, '', 'Estados Unidos'),
('Business', 1, 44, '', 'Estados Unidos'),
('Cleanin'' Out My Closet', 1, 44, '', 'Estados Unidos'),
('Without Me', 1, 44, '', 'Estados Unidos'),
('Sing For The Moment', 1, 44, '', 'Estados Unidos'),
('Superman', 1, 44, 'Dina Rae', 'Estados Unidos'),
('Till I Collapse', 1, 44, 'Nate Dogg', 'Estados Unidos'),
('Kill You', 1, 45, '', 'Estados Unidos'),
('Stan', 1, 45, 'Dido', 'Estados Unidos'),
('The Way I Am', 1, 45, '', 'Estados Unidos'),
('The Real Slim Shady', 1, 45, '', 'Estados Unidos'),
('I''m Back', 1, 45, '', 'Estados Unidos'),
('Drug Ballad', 1, 45, '', 'Estados Unidos'),
('Criminal', 1, 45, '', 'Estados Unidos'),
('Bitch Please II', 1, 45, 'Dr. Dre & Snoop Dogg & Nate Dogg & Xzibit', 'Estados Unidos'),
('How Many Mics', 23, 18, '', 'Estados Unidos'),
('Ready or Not', 23, 18, '', 'Estados Unidos'),
('Zealots', 23, 18, '', 'Estados Unidos'),
('Fu-Ge-La', 23, 18, '', 'Estados Unidos'),
('Killing Me Softly With His Song', 23, 18, '', 'Estados Unidos'),
('No Woman, No Cry', 23, 18, '', 'Estados Unidos'),
('The Score', 23, 18, 'Diamond D', 'Estados Unidos'),
('Nutmeg', 24, 19, 'RZA', 'Estados Unidos'),
('One', 24, 19, '', 'Estados Unidos'),
('Apollo Kids', 24, 19, 'Raekwon', 'Estados Unidos'),
('Buck 50', 24, 19, 'Cappadonna & Method Man & Redman', 'Estados Unidos'),
('Mighty Healthy', 24, 19, '', 'Estados Unidos'),
('Wu Banga 101', 24, 19, 'GZA & Cappadonna & Masta Killa & Raekwon', 'Estados Unidos'),
('Hip Hop', 26, 20, '', 'Estados Unidos'),
('Love', 26, 20, '', 'Estados Unidos'),
('Ms. Fat Booty', 26, 20, '', 'Estados Unidos'),
('Speed Law', 26, 20, '', 'Estados Unidos'),
('UMI Says', 26, 20, '', 'Estados Unidos'),
('Mathematics', 26, 20, '', 'Estados Unidos'),
('Brooklyn', 26, 20, '', 'Estados Unidos'),
('Know That', 26, 20, 'Talib Kweli', 'Estados Unidos'),
('Do It Now', 26, 20, 'Busta Rhymes', 'Estados Unidos'),
('Ether', 17, 21, '', 'Estados Unidos'),
('Got Ur Self A Gun', 17, 21, '', 'Estados Unidos'),
('You''re da Man', 17, 21, '', 'Estados Unidos'),
('One Mic', 17, 21, '', 'Estados Unidos'),
('2nd Childhood', 17, 21, '', 'Estados Unidos'),
('Speechless', 17, 22, '', 'Estados Unidos'),
('40-16 Building', 17, 22, '', 'Estados Unidos'),
('Hollywood Gangsta', 17, 22, '', 'Estados Unidos'),
('Wu for the Children', 17, 22, '', 'Estados Unidos'),
('Wave Gods', 17, 22, 'A$AP Rocky', 'Estados Unidos'),
('Bomb First (My Second Reply)', 16, 23, '', 'Estados Unidos'),
('Hail Mary', 16, 23, '', 'Estados Unidos'),
('To Live And Die In L.A.', 16, 23, '', 'Estados Unidos'),
('Me and My Girlfriend', 16, 23, '', 'Estados Unidos'),
('Against All Odds', 16, 23, '', 'Estados Unidos'),
('Somebody''s Gotta Die', 21, 24, '', 'Estados Unidos'),
('Hypnotize', 21, 24, '', 'Estados Unidos'),
('Kick in the Door', 21, 24, '', 'Estados Unidos'),
('What''s Beef?', 21, 24, '', 'Estados Unidos'),
('Mo Money Mo Problems', 21, 24, 'Puff Daddy & Mase', 'Estados Unidos'),
('Notorius Thugs', 21, 24, '', 'Estados Unidos'),
('I Got a Story to Tell', 21, 24, '', 'Estados Unidos'),
('Ten Crack Commandments', 21, 24, '', 'Estados Unidos'),
('Sky''s the Limit', 21, 24, '112', 'Estados Unidos'),
('Long Kiss Goodnight', 21, 24, '', 'Estados Unidos'),
('You''re Nobody (Til Somebody Kills You)', 21, 24, '', 'Estados Unidos'),
('Straight Outta Compton', 47, 25, '', 'Estados Unidos'),
('Fuck Tha Police', 47, 25, '', 'Estados Unidos'),
('Gangsta Gangsta', 47, 25, '', 'Estados Unidos'),
('Parental Discretion Iz Advised', 47, 25, '', 'Estados Unidos'),
('If It Ain''t Ruff', 47, 25, '', 'Estados Unidos'),
('Shook Ones, Pt. II', 48, 26, '', 'Estados Unidos'),
('Survival of the Fittest', 48, 26, '', 'Estados Unidos'),
('Eye for a Eye (Your Beef Is Mines)', 48, 26, 'Nas & Raekwon', 'Estados Unidos'),
('Give Up the Goods (Just Step)', 48, 26, 'Big Noyd', 'Estados Unidos'),
('Trife Life', 48, 26, '', 'Estados Unidos'),
('Cradle to the Grave', 48, 26, '', 'Estados Unidos'),
('Right Back at You', 48, 26, 'Ghostface Killah & Raekwon & Big Noyd', 'Estados Unidos'),
('Wat''s Wrong', 36, 27, 'Zacari & Kendrick Lamar', 'Estados Unidos'),
('Free Lunch', 36, 27, '', 'Estados Unidos'),
('Park', 36, 27, '', 'Estados Unidos'),
('93 ''Til Infinity', 33, 28, '', 'Estados Unidos'),
('Passin'' Me By', 34, 29, '', 'Estados Unidos'),
('Regulate', 35, 30, 'Nate Dogg', 'Estados Unidos'),
('Astronomy (8th Light)', 27, 31, 'Weldon Irvine', 'Estados Unidos'),
('Definition', 27, 31, '', 'Estados Unidos'),
('Re:Definition', 27, 31, '', 'Estados Unidos'),
('Children''s Story', 27, 31, '', 'Estados Unidos'),
('Brown Skin Lady', 27, 31, '', 'Estados Unidos'),
('Respiration', 27, 31, 'Common', 'Estados Unidos'),
('Thieves In The Night', 27, 31, '', 'Estados Unidos'),
('Beware', 28, 32, '', 'Estados Unidos'),
('Super Lyrical', 28, 32, 'Black Thought', 'Estados Unidos'),
('Still Not a Player', 28, 32, 'Joe', 'Estados Unidos'),
('The Dream Shatterer', 28, 32, '', 'Estados Unidos'),
('You Ain''t a Killer', 28, 32, '', 'Estados Unidos'),
('I''m Not a Player', 28, 32, '', 'Estados Unidos'),
('Boomerang', 28, 32, '', 'Estados Unidos'),
('Parental Discretion', 28, 32, 'Busta Rhymes', 'Estados Unidos'),
('Twinz', 28, 32, 'Fat Joe', 'Estados Unidos'),
('Gin and Juice', 29, 33, '', 'Estados Unidos'),
('Murder Was The Case', 29, 33, '', 'Estados Unidos'),
('Who Am I (What''s My Name)?', 29, 33, '', 'Estados Unidos'),
('You Know My Steez', 30, 34, '', 'Estados Unidos'),
('Work', 30, 34, '', 'Estados Unidos'),
('Above The Clouds', 30, 34, 'Inspectah Deck', 'Estados Unidos'),
('Moment Of Truth', 30, 34, '', 'Estados Unidos'),
('What I''m Here 4', 30, 34, '', 'Estados Unidos'),
('My Advice 2 You', 30, 34, '', 'Estados Unidos'),
('Next Time', 30, 34, '', 'Estados Unidos'),
('ONCE UPON A TIME (FREESTLYE)', 31, 35, 'Denzel Curry', 'Estados Unidos'),
('Shimmy Shimmy Ya', 32, 36, '', 'Estados Unidos'),
('Brooklyn Zoo', 32, 36, '', 'Estados Unidos'),
('Hippa to da Hoppa', 32, 36, '', 'Estados Unidos'),
('Protect Ya Neck II the Zoo', 32, 36, '', 'Estados Unidos'),
('Put It On', 18, 37, '', 'Estados Unidos'),
('MVP', 18, 37, '', 'Estados Unidos'),
('No Endz, No Skinz', 18, 37, '', 'Estados Unidos'),
('8 Iz Enuff', 18, 37, '', 'Estados Unidos'),
('All Black', 18, 37, '', 'Estados Unidos'),
('Danger Zone', 18, 37, '', 'Estados Unidos'),
('Da Graveyard', 18, 37, '', 'Estados Unidos'),
('Street Struck', 18, 37, '', 'Estados Unidos'),
('Let ''Em Have It "L"', 18, 37, '', 'Estados Unidos'),
('Fed Up Wit the Bullshit', 18, 37, '', 'Estados Unidos'),
('Lifestylez Ov Da Poor & Dangerous', 18, 37, '', 'Estados Unidos'),
('Hoe Cakes', 51, 38, '', 'Estados Unidos'),
('One Beer', 51, 38, '', 'Estados Unidos'),
('Deep Fried Frenz', 51, 38, '', 'Estados Unidos'),
('Kon Karne', 51, 38, '', 'Estados Unidos'),
('Vomitspit', 51, 38, '', 'Estados Unidos'),
('Rapp Snitch Knishes', 51, 38, 'Mr. Fantastik', 'Estados Unidos'),
('Hustler''s Ambition', 22, 76, '', 'Estados Unidos'),
('Window Shopper', 22, 76, '', 'Estados Unidos'),
('When It Rains It Pours', 22, 76, '', 'Estados Unidos'),
('Best Friend', 22, 76, '', 'Estados Unidos'),
('I''ll Whip Ya Head Boy', 22, 76, 'Young Buck', 'Estados Unidos'),
('If I Die 2Nite', 3, 77, '', 'Estados Unidos'),
('Me Against The World', 3, 77, 'Dramacydal', 'Estados Unidos'),
('So Many Tears', 3, 77, '', 'Estados Unidos'),
('Temptations', 3, 77, '', 'Estados Unidos'),
('Lord Knows', 3, 77, '', 'Estados Unidos'),
('Dear Mama', 3, 77, '', 'Estados Unidos'),
('It Ain''t Easy', 3, 77, '', 'Estados Unidos'),
('Old School', 3, 77, '', 'Estados Unidos'),
('Piggy Bank', 22, 78, '', 'Estados Unidos'),
('Candy Shop', 22, 78, 'Olivia', 'Estados Unidos'),
('Disco Inferno', 22, 78, '', 'Estados Unidos'),
('Just A Lil Bit', 22, 78, '', 'Estados Unidos'),
('Jorge da Capadócia', 40, 50, '', 'Brasil'),
('Capítulo 4, Versículo 3', 40, 50, '', 'Brasil'),
('Tô Ouvindo Alguém Me Chamar', 40, 50, '', 'Brasil'),
('Diário de um Detento', 40, 50, '', 'Brasil'),
('Qual Mentira Vou Acreditar', 40, 50, '', 'Brasil'),
('Mágico de Oz', 40, 50, '', 'Brasil'),
('Fórmula Mágica de Paz', 40, 50, '', 'Brasil'),
('Sou + Você', 40, 51, '', 'Brasil'),
('Vida Loka, Pt.1', 40, 51, '', 'Brasil'),
('Nego Drama', 40, 51, '', 'Brasil'),
('A Vítima', 40, 51, '', 'Brasil'),
('Eu Sou 157', 40, 51, '', 'Brasil'),
('A Vida É Desafio', 40, 51, 'Afro-X', 'Brasil'),
('1 por Amor, 2 por Dinheiro', 40, 51, '', 'Brasil'),
('Otus 500', 40, 51, '', 'Brasil'),
('Crime Vai e Vem', 40, 51, '', 'Brasil'),
('Jesus Chorou', 40, 51, '', 'Brasil'),
('Estilo Cachorro', 40, 51, '', 'Brasil'),
('Vida Loka, Pt.2', 40, 51, '', 'Brasil'),
('Expresso da Meia-Noite', 40, 51, '', 'Brasil'),
('Da Ponte pra Cá', 40, 51, '', 'Brasil'),
('Sigo na Sombra', 41, 52, '', 'Brasil'),
('Quadros', 41, 52, 'Luccas Carlos & Ashira', 'Brasil'),
('O Que Sobra Disso Tudo', 41, 52, 'Luccas Carlos', 'Brasil'),
('Visão Ampla', 41, 52, '', 'Brasil'),
('Caminhos', 41, 52, '', 'Brasil'),
('Castelos & Ruínas', 41, 52, '', 'Brasil'),
('Pirâmide', 41, 52, '', 'Brasil'),
('Amores, Vícios e Obsessões', 41, 52, '', 'Brasil'),
('Não Me Espere', 41, 52, '', 'Brasil'),
('Um Dia de Chuva Qualquer', 41, 52, '', 'Brasil'),
('O Próximo Nascer do Sol', 41, 52, '', 'Brasil'),
('Novo Poder', 41, 53, '', 'Brasil'),
('Porcentos', 41, 53, '', 'Brasil'),
('Gigantes', 41, 53, 'Juyè', 'Brasil'),
('Julius', 41, 53, '', 'Brasil'),
('Abebe Bikila', 41, 53, '', 'Brasil'),
('Titãs', 41, 53, '', 'Brasil'),
('Jovens', 41, 53, '', 'Brasil'),
('Falam', 41, 53, 'Sain & Marcelo D2', 'Brasil'),
('Correria - Remix', 41, 53, 'Akira Presidente & Drik Barbosa & Papatinho', 'Brasil'),
('Deus do Furdunço', 41, 53, '', 'Brasil'),
('Meu santo tá cansado', 42, 54, '', 'Brasil'),
('Hóstia', 42, 54, '', 'Brasil'),
('Meu mundo é o barro', 42, 54, '', 'Brasil'),
('Monstro invisível', 42, 54, '', 'Brasil'),
('Súplica cearense', 42, 54, '', 'Brasil'),
('Fininho da vida', 42, 54, '', 'Brasil'),
('Respeito pela mais bela', 42, 54, '', 'Brasil'),
('Vários holofotes', 42, 54, '', 'Brasil'),
('Tribunal de rua', 42, 55, '', 'Brasil'),
('Me deixa', 42, 55, '', 'Brasil'),
('O que sobrou do céu', 42, 55, '', 'Brasil'),
('Se não avisar o bicho pega', 42, 55, '', 'Brasil'),
('Minha alma (A paz que eu não quero)', 42, 55, '', 'Brasil'),
('Lado B lado A', 42, 55, '', 'Brasil'),
('Homem amarelo', 42, 55, '', 'Brasil'),
('Confisco', 43, 56, '', 'Brasil'),
('Zóio De Lula', 43, 56, '', 'Brasil'),
('Te Levar Daqui', 43, 56, '', 'Brasil'),
('O Preço', 43, 56, '', 'Brasil'),
('Não Deixe O Mar Te Engolir', 43, 56, '', 'Brasil'),
('Hoje Eu Acordei Feliz', 43, 57, '', 'Brasil'),
('Sino Dourado', 43, 57, '', 'Brasil'),
('Quebra-Mar', 43, 57, '', 'Brasil'),
('Lugar Ao Sol', 43, 57, '', 'Brasil'),
('Como Tudo Deve Ser', 43, 57, '', 'Brasil'),
('Tudo Pro Alto', 43, 57, '', 'Brasil'),
('Dona do Meu Pensamento', 43, 58, '', 'Brasil'),
('Me Encontra', 43, 58, '', 'Brasil'),
('Só Os Loucos Sabem', 43, 58, '', 'Brasil'),
('Só Existe o Agora', 43, 58, '', 'Brasil'),
('Viver Dias de Sol', 43, 58, '', 'Brasil'),
('Só Pra Vadiar', 43, 58, '', 'Brasil'),
('RADDIM', 44, 59, '', 'Brasil'),
('FALA MEMO', 44, 59, 'Coruja Bc1', 'Brasil'),
('TERCEIRO MUNDO', 44, 59, '', 'Brasil'),
('CHELSEA', 44, 59, '', 'Brasil'),
('YIN YANG', 44, 59, '', 'Brasil'),
('SOHO', 44, 59, 'Luccas Carlos', 'Brasil'),
('GOLPE', 44, 60, '', 'Brasil'),
('HOJE', 44, 60, '', 'Brasil'),
('SOBE O MORRO', 44, 60, '', 'Brasil'),
('NEM ME LIGA', 44, 60, 'Smile', 'Brasil'),
('O Que Separa os Meninos dos Homens', 45, 61, '', 'Brasil'),
('B.O.', 45, 61, 'MC Coé', 'Brasil'),
('O Tempo Passou', 45, 61, 'Mc Marechal', 'Brasil'),
('Coragem', 45, 61, '', 'Brasil'),
('O Mundo ao Norte', 45, 61, '', 'Brasil'),
('Prantos', 45, 62, '', 'Brasil'),
('Puxa o Gatilho Primeiro', 45, 62, '', 'Brasil'),
('Adidas & Nike', 45, 62, '', 'Brasil'),
('Gestão', 45, 62, '', 'Brasil'),
('Do Falcão', 45, 62, '', 'Brasil'),
('Pertence ao Crime', 45, 62, '', 'Brasil'),
('AQL SLV', 45, 62, 'SD9 & VND & Tiago Mac', 'Brasil'),
('Bônus', 45, 62, '', 'Brasil'),
('Bebeto & Romário', 45, 63, '', 'Brasil'),
('O Terror Voltou', 45, 63, '', 'Brasil'),
('9mm', 45, 63, '', 'Brasil'),
('Vivências', 45, 63, '', 'Brasil'),
('E Essas Dores Não São Nem Metade', 45, 63, '', 'Brasil'),
('Cenas Excluídas', 45, 63, '', 'Brasil'),
('Ar & Água', 45, 63, '', 'Brasil'),
('NOITES DO SUBÚRBIO', 45, 64, 'Jotapê & Mc Marechal', 'Brasil'),
('SANTORUA', 45, 64, '', 'Brasil'),
('NQL BECO', 45, 64, 'AçúK & Borges', 'Brasil'),
('DESCARRILHADO', 45, 64, '', 'Brasil'),
('QUAL FOI', 45, 64, 'Murica & Lis Mc', 'Brasil'),
('SE N AVISA O BICHO PEGA', 45, NULL, '', 'Brasil'),
('QUOTIDIANO', 45, NULL, '', 'Brasil'),
('ABAIXO DO RADAR', 49, 79, 'Smile', 'Brasil'),
('OBRIGADO MAINSTREAM', 49, 79, '', 'Brasil'),
('CHUCRO BUARQUE', 49, 79, '', 'Brasil'),
('SUPER HIP-HOP', 49, 79, '', 'Brasil'),
('NÓIS É ISSO AÍ', 49, 79, '', 'Brasil'),
('MAIS UM DIA', 49, 79, '', 'Brasil'),
('RELÓGIO', 49, 79, '', 'Brasil'),
('O DOBRO OU NADA', 49, 79, '', 'Brasil'),
('RELÓGIO', 49, 79, '', 'Brasil'),
('The Birds Don''t Sing', 52, 81, 'John Legend', 'Estados Unidos'),
('So Be It', 52, 81, '', 'Estados Unidos'),
('Ace Trumpets', 52, 81, '', 'Estados Unidos'),
('Chains & Whips', 52, 81, 'Kendrick Lamar', 'Estados Unidos'),
('Buggin'' Out', 53, 82, '', 'Estados Unidos'),
('Rap Promoter', 53, 82, '', 'Estados Unidos'),
('Check the Rhime', 53, 82, '', 'Estados Unidos'),
('Vibes and Stuff', 53, 82, '', 'Estados Unidos'),
('Jazz (We''ve Got)', 53, 82, '', 'Estados Unidos'),
('Scenario', 53, 82, 'Busta Rhymes & Dinco D & Charlie Brown', 'Estados Unidos'),
('Show Business', 53, 82, 'Diamond D & Lord Jamar & Sadat X', 'Estados Unidos'),
('ATÍPICO', 54, 83, '', 'Brasil'),
('JUNHO DE 94', 54, 83, '', 'Brasil'),
('1010', 54, 83, '', 'Brasil'),
('SOLTO', 54, 83, 'Hot', 'Brasil'),
('UFA', 54, 83, 'Sidoka & Sant', 'Brasil'),
('CORRA', 54, 83, 'Paige', 'Brasil'),
('CANÇÃO PRO MEU FILHO', 54, 83, '', 'Brasil'),
('Entre o Código da Espada e o Perfume da Rosa', 54, 84, '', 'Brasil'),
('Esquimó', 54, 84, '', 'Brasil'),
('Santa Ceia', 54, 84, 'Yodabren', 'Brasil'),
('Verdades Inventadas', 54, 84, '', 'Brasil'),
('Geminiano', 54, 84, '', 'Brasil'),
('O Mundo é Nosso', 54, 84, 'BK', 'Brasil'),
('Rotina', 55, 85, '', 'Brasil'),
('Sozim', 55, 85, '', 'Brasil'),
('E.M.I.C.I.D.A (Adoooro)', 55, 85, '', 'Brasil'),
('Só Isso', 55, 85, '', 'Brasil'),
('Vou Busca Minha Fulô', 55, 85, '', 'Brasil'),
('A Cada Vento', 55, 85, '', 'Brasil'),
('Sei Lá', 55, 85, '', 'Brasil'),
('Essa É Pra Você Primo', 55, 85, '', 'Brasil'),
('Eu Tô Bem', 55, 85, '', 'Brasil');
